BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_raster;
CREATE EXTENSION IF NOT EXISTS timescaledb;

ALTER DATABASE !DATABASE! SET postgis.gdal.enabled_drivers = 'ENABLE_ALL';
ALTER DATABASE !DATABASE! SET postgis.enable_outdb_rasters = True;

CREATE SCHEMA IF NOT EXISTS !SCHEMA!;
CREATE TABLE IF NOT EXISTS !SCHEMA!.!PRODUCT! ( id serial NOT NULL, fdate TIMESTAMP NOT NULL,  fid INT NOT NULL, rid INT NOT NULL, rast raster );

SELECT create_hypertable(  '!SCHEMA!.!PRODUCT!', 'fdate', if_not_exists => TRUE );

CREATE TABLE IF NOT EXISTS !SCHEMA!.product ( id serial NOT NULL PRIMARY KEY, name VARCHAR UNIQUE, description VARCHAR, keywords VARCHAR );
ALTER TABLE !SCHEMA!.product ADD UNIQUE (name);

CREATE TABLE IF NOT EXISTS !SCHEMA!.measurement ( id serial NOT NULL PRIMARY KEY, pid INT NOT NULL, name VARCHAR NOT NULL, description VARCHAR, keywords VARCHAR, units VARCHAR );
ALTER TABLE !SCHEMA!.measurement ADD UNIQUE (pid, name);

CREATE TABLE IF NOT EXISTS !SCHEMA!.cat ( id serial NOT NULL PRIMARY KEY, fdate TIMESTAMP NOT NULL, fid INT NOT NULL, pid INT NOT NULL, pathname VARCHAR(255) NOT NULL, hull GEOMETRY ); 

CREATE SEQUENCE IF NOT EXISTS fid_!SCHEMA!_!PRODUCT!_seq;
END;
